version: '3.5'

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    container_name: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - internal_network

  back-end:
    build:
      context: ./back-end
      dockerfile: ./Dockerfile
    container_name: back-end
    networks:
      - internal_network
    depends_on:
      - db
    volumes:
      - ./back-end/src:/app/src

  front-end:
    build:
      context: ./front-end
      dockerfile: ./Dockerfile
    container_name: front-end
    ports:
      - '3001:3000'
    networks:
      - internal_network
    depends_on:
      - db
    volumes:
      - ./front-end/src:/app/src

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - '5050:80'
    networks:
      - internal_network
    depends_on:
      - db

networks:
  internal_network:

